-- Antigravity ChatGPT Agent Bridge schema
-- Apply to the dedicated Supabase project used only for ChatGPT <-> Termux/AGY jobs.

begin;

create table if not exists public.agent_jobs (
  id uuid primary key default gen_random_uuid(),
  idempotency_key text not null unique default gen_random_uuid()::text,
  requested_by text not null default 'chatgpt',
  status text not null default 'pending'
    check (status in ('pending','claimed','running','completed','failed','cancelled')),
  request jsonb not null default '{}'::jsonb,
  conversation_id text,
  worker_id text,
  claim_token uuid,
  attempts integer not null default 0 check (attempts >= 0),
  heartbeat_at timestamptz,
  lease_expires_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  error jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agent_jobs_request_object check (jsonb_typeof(request) = 'object'),
  constraint agent_jobs_prompt_required check (length(btrim(coalesce(request->>'prompt',''))) > 0)
);

create index if not exists agent_jobs_queue_idx
  on public.agent_jobs(status, created_at) where status='pending';
create index if not exists agent_jobs_worker_lease_idx
  on public.agent_jobs(worker_id, lease_expires_at) where status in ('claimed','running');

create table if not exists public.agent_events (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.agent_jobs(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint agent_events_payload_object check (jsonb_typeof(payload)='object')
);
create index if not exists agent_events_job_idx on public.agent_events(job_id,id);

create table if not exists public.agent_results (
  job_id uuid primary key references public.agent_jobs(id) on delete cascade,
  conversation_id text,
  response_text text not null default '',
  bot_message jsonb,
  subagents jsonb not null default '[]'::jsonb,
  tasks jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  constraint agent_results_subagents_array check (jsonb_typeof(subagents)='array'),
  constraint agent_results_tasks_array check (jsonb_typeof(tasks)='array')
);

alter table public.agent_jobs enable row level security;
alter table public.agent_events enable row level security;
alter table public.agent_results enable row level security;

revoke all on table public.agent_jobs from anon, authenticated;
revoke all on table public.agent_events from anon, authenticated;
revoke all on table public.agent_results from anon, authenticated;

grant select,insert,update,delete on table public.agent_jobs to service_role;
grant select,insert,update,delete on table public.agent_events to service_role;
grant select,insert,update,delete on table public.agent_results to service_role;
grant usage,select on sequence public.agent_events_id_seq to service_role;

create or replace function public.claim_agent_job(p_worker_id text,p_lease_seconds integer default 120)
returns setof public.agent_jobs
language plpgsql security invoker set search_path=public
as $$
begin
  if p_worker_id is null or btrim(p_worker_id)='' then raise exception 'worker_id_required'; end if;
  if p_lease_seconds<30 or p_lease_seconds>900 then raise exception 'invalid_lease_seconds'; end if;
  return query
  with candidate as (
    select id from public.agent_jobs
    where status='pending'
    order by created_at,id
    for update skip locked
    limit 1
  )
  update public.agent_jobs j
  set status='claimed',worker_id=p_worker_id,claim_token=gen_random_uuid(),
      attempts=j.attempts+1,heartbeat_at=now(),
      lease_expires_at=now()+make_interval(secs=>p_lease_seconds),
      updated_at=now(),error=null
  from candidate c where j.id=c.id
  returning j.*;
end;
$$;

create or replace function public.heartbeat_agent_job(
  p_job_id uuid,p_worker_id text,p_claim_token uuid,p_lease_seconds integer default 120
) returns boolean
language plpgsql security invoker set search_path=public
as $$
declare n integer;
begin
  if p_lease_seconds<30 or p_lease_seconds>900 then raise exception 'invalid_lease_seconds'; end if;
  update public.agent_jobs
  set heartbeat_at=now(),lease_expires_at=now()+make_interval(secs=>p_lease_seconds),updated_at=now()
  where id=p_job_id and worker_id=p_worker_id and claim_token=p_claim_token
    and status in ('claimed','running');
  get diagnostics n=row_count; return n=1;
end;
$$;

create or replace function public.mark_agent_job_running(
  p_job_id uuid,p_worker_id text,p_claim_token uuid,p_conversation_id text default null,p_lease_seconds integer default 120
) returns boolean
language plpgsql security invoker set search_path=public
as $$
declare n integer;
begin
  update public.agent_jobs
  set status='running',conversation_id=coalesce(nullif(p_conversation_id,''),conversation_id),
      started_at=coalesce(started_at,now()),heartbeat_at=now(),
      lease_expires_at=now()+make_interval(secs=>p_lease_seconds),updated_at=now()
  where id=p_job_id and worker_id=p_worker_id and claim_token=p_claim_token
    and status in ('claimed','running');
  get diagnostics n=row_count; return n=1;
end;
$$;

create or replace function public.bind_agent_job_conversation(
  p_job_id uuid,p_worker_id text,p_claim_token uuid,p_conversation_id text
) returns boolean
language plpgsql security invoker set search_path=public
as $$
declare n integer;
begin
  if p_conversation_id is null or btrim(p_conversation_id)='' then return false; end if;
  update public.agent_jobs set conversation_id=p_conversation_id,updated_at=now()
  where id=p_job_id and worker_id=p_worker_id and claim_token=p_claim_token
    and status in ('claimed','running');
  get diagnostics n=row_count; return n=1;
end;
$$;

create or replace function private.write_agent_result(
  p_job_id uuid,
  p_conversation_id text,
  p_response_text text,
  p_bot_message jsonb,
  p_subagents jsonb,
  p_tasks jsonb
) returns void
language plpgsql
security definer
set search_path = private, public
as $
begin
  insert into public.agent_results(job_id,conversation_id,response_text,bot_message,subagents,tasks,created_at)
  values(
    p_job_id,
    nullif(p_conversation_id,''),
    coalesce(p_response_text,''),
    p_bot_message,
    coalesce(p_subagents,'[]'::jsonb),
    coalesce(p_tasks,'[]'::jsonb),
    now()
  )
  on conflict(job_id) do update set
    conversation_id=excluded.conversation_id,
    response_text=excluded.response_text,
    bot_message=excluded.bot_message,
    subagents=excluded.subagents,
    tasks=excluded.tasks,
    created_at=excluded.created_at;
end;
$;

grant usage on schema private to anon, service_role;
grant execute on function private.write_agent_result(uuid,text,text,jsonb,jsonb,jsonb) to anon, service_role;

create or replace function public.complete_agent_job(
  p_job_id uuid,p_worker_id text,p_claim_token uuid,p_conversation_id text,p_response_text text,
  p_bot_message jsonb default null,p_subagents jsonb default '[]'::jsonb,p_tasks jsonb default '[]'::jsonb
) returns boolean
language plpgsql
security invoker
set search_path=public,private
as $
declare n integer;
begin
  update public.agent_jobs
  set status='completed',
      conversation_id=coalesce(nullif(p_conversation_id,''),conversation_id),
      completed_at=now(),
      heartbeat_at=now(),
      lease_expires_at=null,
      updated_at=now(),
      error=null
  where id=p_job_id and worker_id=p_worker_id and claim_token=p_claim_token
    and status in ('claimed','running');

  get diagnostics n=row_count;
  if n<>1 then return false; end if;

  perform private.write_agent_result(
    p_job_id,
    p_conversation_id,
    p_response_text,
    p_bot_message,
    p_subagents,
    p_tasks
  );

  return true;
end;
$;

create or replace function public.fail_agent_job(
  p_job_id uuid,p_worker_id text,p_claim_token uuid,p_error jsonb
) returns boolean
language plpgsql security invoker set search_path=public
as $$
declare n integer;
begin
  update public.agent_jobs
  set status='failed',completed_at=now(),heartbeat_at=now(),lease_expires_at=null,
      updated_at=now(),error=coalesce(p_error,'{"code":"unknown"}'::jsonb)
  where id=p_job_id and worker_id=p_worker_id and claim_token=p_claim_token
    and status in ('claimed','running');
  get diagnostics n=row_count; return n=1;
end;
$$;

create or replace function public.requeue_stale_claimed_agent_job(
  p_job_id uuid,p_worker_id text,p_claim_token uuid
) returns boolean
language plpgsql security invoker set search_path=public
as $$
declare n integer;
begin
  update public.agent_jobs
  set status='pending',worker_id=null,claim_token=null,heartbeat_at=null,lease_expires_at=null,updated_at=now()
  where id=p_job_id and worker_id=p_worker_id and claim_token=p_claim_token
    and status='claimed' and started_at is null and lease_expires_at<now();
  get diagnostics n=row_count; return n=1;
end;
$$;

revoke all on function public.claim_agent_job(text,integer) from public,anon,authenticated;
revoke all on function public.heartbeat_agent_job(uuid,text,uuid,integer) from public,anon,authenticated;
revoke all on function public.mark_agent_job_running(uuid,text,uuid,text,integer) from public,anon,authenticated;
revoke all on function public.bind_agent_job_conversation(uuid,text,uuid,text) from public,anon,authenticated;
revoke all on function public.complete_agent_job(uuid,text,uuid,text,text,jsonb,jsonb,jsonb) from public,anon,authenticated;
revoke all on function public.fail_agent_job(uuid,text,uuid,jsonb) from public,anon,authenticated;
revoke all on function public.requeue_stale_claimed_agent_job(uuid,text,uuid) from public,anon,authenticated;

grant execute on function public.claim_agent_job(text,integer) to service_role;
grant execute on function public.heartbeat_agent_job(uuid,text,uuid,integer) to service_role;
grant execute on function public.mark_agent_job_running(uuid,text,uuid,text,integer) to service_role;
grant execute on function public.bind_agent_job_conversation(uuid,text,uuid,text) to service_role;
grant execute on function public.complete_agent_job(uuid,text,uuid,text,text,jsonb,jsonb,jsonb) to service_role;
grant execute on function public.fail_agent_job(uuid,text,uuid,jsonb) to service_role;
grant execute on function public.requeue_stale_claimed_agent_job(uuid,text,uuid) to service_role;


-- Device-scoped bridge authentication. The raw client secret never needs to leave Termux.
create schema if not exists private;

create table if not exists private.bridge_client_keys (
  key_id text primary key,
  secret_sha256 text not null check (secret_sha256 ~ '^[0-9a-f]{64}
),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

revoke all on schema private from public, anon, authenticated;
revoke all on table private.bridge_client_keys from public, anon, authenticated;

create or replace function private.bridge_check_request()
returns void
language plpgsql
security definer
set search_path = private, public
as $
declare
  jwt_role text := coalesce(
    current_setting('request.jwt.claims', true)::jsonb->>'role',
    current_setting('request.jwt', true)::jsonb->>'role'
  );
  supplied text := current_setting('request.headers', true)::jsonb->>'x-antigravity-bridge-key';
  supplied_hash text;
  ok boolean;
begin
  if jwt_role = 'service_role' then return; end if;
  if jwt_role <> 'anon' then
    raise sqlstate 'PGRST' using
      message = '{"message":"Forbidden"}',
      detail = '{"status":403,"status_text":"Forbidden"}';
  end if;
  if supplied is null or length(supplied) < 32 then
    raise sqlstate 'PGRST' using
      message = '{"message":"Missing bridge key"}',
      detail = '{"status":403,"status_text":"Forbidden"}';
  end if;
  supplied_hash := encode(sha256(convert_to(supplied, 'utf8')), 'hex');
  select exists(
    select 1 from private.bridge_client_keys
    where enabled = true and secret_sha256 = supplied_hash
  ) into ok;
  if not ok then
    raise sqlstate 'PGRST' using
      message = '{"message":"Invalid bridge key"}',
      detail = '{"status":403,"status_text":"Forbidden"}';
  end if;
end;
$;

revoke all on function private.bridge_check_request() from public, authenticated;
grant usage on schema private to anon, service_role;
grant execute on function private.bridge_check_request() to anon, service_role;

alter role authenticator set pgrst.db_pre_request = 'private.bridge_check_request';

grant select, update on table public.agent_jobs to anon;
grant insert on table public.agent_events to anon;
grant select on table public.agent_results to anon;
grant usage, select on sequence public.agent_events_id_seq to anon;

create policy bridge_anon_jobs_select on public.agent_jobs for select to anon using (true);
create policy bridge_anon_jobs_update on public.agent_jobs for update to anon using (true) with check (true);
create policy bridge_anon_events_insert on public.agent_events for insert to anon with check (true);
create policy bridge_anon_results_select on public.agent_results for select to anon using (true);

grant execute on function public.claim_agent_job(text,integer) to anon;
grant execute on function public.heartbeat_agent_job(uuid,text,uuid,integer) to anon;
grant execute on function public.mark_agent_job_running(uuid,text,uuid,text,integer) to anon;
grant execute on function public.bind_agent_job_conversation(uuid,text,uuid,text) to anon;
grant execute on function public.complete_agent_job(uuid,text,uuid,text,text,jsonb,jsonb,jsonb) to anon;
grant execute on function public.fail_agent_job(uuid,text,uuid,jsonb) to anon;
grant execute on function public.requeue_stale_claimed_agent_job(uuid,text,uuid) to anon;

create or replace function private.wait_agent_job(
  p_job_id pg_catalog.uuid,
  p_timeout_seconds pg_catalog.integer default 20,
  p_poll_interval_ms pg_catalog.integer default 500
) returns pg_catalog.jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_timeout_seconds pg_catalog.integer;
  v_poll_interval_ms pg_catalog.integer;
  v_deadline pg_catalog.timestamptz;
  v_job record;
  v_event record;
  v_status pg_catalog.text;
  v_terminal pg_catalog.boolean;
  v_ready pg_catalog.boolean;
  v_response_text pg_catalog.text;
  v_conversation_id pg_catalog.text;
  v_error pg_catalog.jsonb;
  v_bot_message pg_catalog.jsonb;
  v_subagents pg_catalog.jsonb;
  v_tasks pg_catalog.jsonb;
  v_progress_seq pg_catalog.bigint;
  v_progress_text pg_catalog.text;
  v_progress_event_type pg_catalog.text;
  v_tool_name pg_catalog.text;
  v_tool_state pg_catalog.text;
begin
  if p_job_id is null then
    return pg_catalog.jsonb_build_object(
      'error', 'job_id_required',
      'found', false,
      'status', null,
      'kind', 'progress',
      'timed_out', false,
      'terminal', false,
      'ready', false,
      'progress_seq', 0,
      'progress_text', null
    );
  end if;

  -- Clamp timeout: 0 to 30 seconds (0 allows instant snapshot check)
  v_timeout_seconds := pg_catalog.least(pg_catalog.greatest(pg_catalog.coalesce(p_timeout_seconds, 20), 0), 30);
  -- Clamp poll interval: 100ms to 5000ms
  v_poll_interval_ms := pg_catalog.least(pg_catalog.greatest(pg_catalog.coalesce(p_poll_interval_ms, 500), 100), 5000);
  v_deadline := pg_catalog.clock_timestamp() + pg_catalog.make_interval(secs => v_timeout_seconds);

  loop
    select
      j.id,
      j.status,
      j.conversation_id as job_conversation_id,
      j.worker_id,
      j.attempts,
      j.heartbeat_at,
      j.lease_expires_at,
      j.started_at,
      j.completed_at,
      j.error,
      j.created_at,
      j.updated_at,
      r.conversation_id as result_conversation_id,
      r.response_text,
      r.bot_message,
      r.subagents,
      r.tasks
    into v_job
    from public.agent_jobs j
    left join public.agent_results r on r.job_id = j.id
    where j.id = p_job_id;

    if not found then
      return pg_catalog.jsonb_build_object(
        'job_id', p_job_id,
        'found', false,
        'status', null,
        'kind', 'progress',
        'timed_out', false,
        'terminal', false,
        'ready', false,
        'progress_seq', 0,
        'progress_text', null
      );
    end if;

    v_status := v_job.status;
    v_terminal := v_status in ('completed', 'failed', 'cancelled');
    v_response_text := pg_catalog.coalesce(v_job.response_text, '');
    v_conversation_id := pg_catalog.coalesce(pg_catalog.nullif(v_job.result_conversation_id, ''), v_job.job_conversation_id);
    v_error := v_job.error;
    v_bot_message := v_job.bot_message;
    v_subagents := pg_catalog.coalesce(v_job.subagents, '[]'::pg_catalog.jsonb);
    v_tasks := pg_catalog.coalesce(v_job.tasks, '[]'::pg_catalog.jsonb);

    -- Fetch latest progress event if available
    select
      e.id,
      e.event_type,
      e.payload
    into v_event
    from public.agent_events e
    where e.job_id = p_job_id
    order by e.id desc
    limit 1;

    if v_event.id is not null then
      v_progress_seq := v_event.id;
      v_progress_event_type := v_event.event_type;
      v_tool_name := pg_catalog.nullif(v_event.payload->'tool'->>'name', '');
      v_tool_state := pg_catalog.nullif(v_event.payload->'tool'->>'state', '');
      v_progress_text := pg_catalog.coalesce(
        pg_catalog.nullif(v_event.payload->>'toolAction', ''),
        pg_catalog.nullif(v_event.payload->>'toolSummary', ''),
        pg_catalog.nullif(v_event.payload->>'message', ''),
        pg_catalog.nullif(v_event.payload->>'status', ''),
        pg_catalog.nullif(v_event.payload->>'summary', ''),
        case
          when v_tool_name is not null and v_tool_state is not null then v_tool_name || ' ' || v_tool_state
          when v_tool_name is not null then v_tool_name
          else null
        end,
        pg_catalog.nullif(v_event.event_type, '')
      );
    else
      v_progress_seq := 0;
      v_progress_text := null;
      v_progress_event_type := null;
      v_tool_name := null;
      v_tool_state := null;
    end if;

    -- Canonical ready evaluation:
    -- completed: ready when non-empty response_text, durable conversation_id, and error null
    -- failed/cancelled: ready = true (terminal result ready to inspect)
    -- non-terminal: ready = false
    if v_status = 'completed' then
      v_ready := (
        pg_catalog.length(pg_catalog.btrim(v_response_text)) > 0
        and v_conversation_id is not null
        and pg_catalog.length(pg_catalog.btrim(v_conversation_id)) > 0
        and v_error is null
      );
    elsif v_terminal then
      v_ready := true;
    else
      v_ready := false;
    end if;

    if v_terminal then
      return pg_catalog.jsonb_build_object(
        'job_id', v_job.id,
        'found', true,
        'status', v_status,
        'kind', 'final',
        'terminal', true,
        'ready', v_ready,
        'timed_out', false,
        'conversation_id', v_conversation_id,
        'response_text', v_response_text,
        'error', v_error,
        'bot_message', v_bot_message,
        'subagents', v_subagents,
        'tasks', v_tasks,
        'worker_id', v_job.worker_id,
        'attempts', v_job.attempts,
        'heartbeat_at', v_job.heartbeat_at,
        'lease_expires_at', v_job.lease_expires_at,
        'started_at', v_job.started_at,
        'completed_at', v_job.completed_at,
        'progress_seq', v_progress_seq,
        'progress_text', v_progress_text,
        'progress_event_type', v_progress_event_type,
        'tool_name', v_tool_name,
        'tool_state', v_tool_state
      );
    end if;

    if pg_catalog.clock_timestamp() >= v_deadline then
      return pg_catalog.jsonb_build_object(
        'job_id', v_job.id,
        'found', true,
        'status', v_status,
        'kind', 'progress',
        'terminal', false,
        'ready', false,
        'timed_out', (v_timeout_seconds > 0),
        'conversation_id', v_conversation_id,
        'response_text', v_response_text,
        'error', v_error,
        'bot_message', v_bot_message,
        'subagents', v_subagents,
        'tasks', v_tasks,
        'worker_id', v_job.worker_id,
        'attempts', v_job.attempts,
        'heartbeat_at', v_job.heartbeat_at,
        'lease_expires_at', v_job.lease_expires_at,
        'started_at', v_job.started_at,
        'completed_at', v_job.completed_at,
        'progress_seq', v_progress_seq,
        'progress_text', v_progress_text,
        'progress_event_type', v_progress_event_type,
        'tool_name', v_tool_name,
        'tool_state', v_tool_state
      );
    end if;

    perform pg_catalog.pg_sleep(v_poll_interval_ms / 1000.0);
  end loop;
end;
$$;

revoke all on function private.wait_agent_job(pg_catalog.uuid, pg_catalog.integer, pg_catalog.integer) from public, anon, authenticated;
grant execute on function private.wait_agent_job(pg_catalog.uuid, pg_catalog.integer, pg_catalog.integer) to service_role;

commit;
notify pgrst,'reload config';
notify pgrst,'reload schema';


-- Request optimization (2026-10-01)

create or replace function public.record_agent_event(
  p_job_id uuid,
  p_worker_id text,
  p_claim_token uuid,
  p_event_type text,
  p_payload jsonb default '{}'::jsonb,
  p_lease_seconds integer default 180
) returns bigint
language plpgsql
security invoker
set search_path=public
as $$
declare
  n integer;
  v_event_id bigint;
begin
  if p_lease_seconds < 30 or p_lease_seconds > 900 then
    raise exception 'invalid_lease_seconds';
  end if;

  update public.agent_jobs
  set heartbeat_at=now(),
      lease_expires_at=now()+make_interval(secs=>p_lease_seconds),
      updated_at=now()
  where id=p_job_id
    and worker_id=p_worker_id
    and claim_token=p_claim_token
    and status in ('claimed','running');
  get diagnostics n=row_count;
  if n<>1 then return null; end if;

  insert into public.agent_events(job_id,event_type,payload)
  values(p_job_id,p_event_type,coalesce(p_payload,'{}'::jsonb))
  returning id into v_event_id;

  return v_event_id;
end;
$$;

revoke all on function public.record_agent_event(uuid,text,uuid,text,jsonb,integer) from public,anon,authenticated;
grant execute on function public.record_agent_event(uuid,text,uuid,text,jsonb,integer) to service_role;

create or replace function private.wait_agent_job(
  p_job_id uuid,
  p_after_seq bigint,
  p_timeout_seconds integer default 20,
  p_poll_interval_ms integer default 500
) returns jsonb
language plpgsql
set search_path to ''
as $function$
declare
  v_started_at timestamptz := pg_catalog.clock_timestamp();
  v_deadline timestamptz;
  v_status text;
  v_job_conversation_id text;
  v_result_conversation_id text;
  v_response_text text;
  v_error jsonb;
  v_heartbeat_at timestamptz;
  v_completed_at timestamptz;
  v_sleep_seconds double precision;
  v_progress_seq bigint;
  v_event_type text;
  v_event_payload jsonb;
  v_progress_text text;
  v_tool_name text;
  v_tool_state text;
  v_changed boolean;
begin
  if p_job_id is null then raise exception 'p_job_id is required'; end if;
  if p_timeout_seconds < 0 or p_timeout_seconds > 30 then
    raise exception 'p_timeout_seconds must be between 0 and 30';
  end if;
  if p_poll_interval_ms < 100 or p_poll_interval_ms > 5000 then
    raise exception 'p_poll_interval_ms must be between 100 and 5000';
  end if;

  v_deadline := v_started_at + pg_catalog.make_interval(secs => p_timeout_seconds);
  v_sleep_seconds := p_poll_interval_ms::double precision / 1000.0;

  loop
    select j.status,j.conversation_id,j.error,j.heartbeat_at,j.completed_at,
           r.conversation_id,r.response_text
    into v_status,v_job_conversation_id,v_error,v_heartbeat_at,v_completed_at,
         v_result_conversation_id,v_response_text
    from public.agent_jobs j
    left join public.agent_results r on r.job_id=j.id
    where j.id=p_job_id;

    if not found then
      return pg_catalog.jsonb_build_object(
        'kind','final','job_id',p_job_id,'status','not_found','terminal',true,
        'ready',false,'timed_out',false,'changed',true,
        'progress_seq',null,'progress_event_type',null,'tool_name',null,'tool_state',null
      );
    end if;

    select e.id,e.event_type,e.payload
    into v_progress_seq,v_event_type,v_event_payload
    from public.agent_events e
    where e.job_id=p_job_id
    order by e.id desc limit 1;

    v_tool_name := nullif(v_event_payload->'tool'->>'name','');
    v_tool_state := nullif(v_event_payload->'tool'->>'state','');
    v_progress_text := case
      when v_event_type='tool_update' then pg_catalog.concat_ws(' ','tool',v_tool_name,v_tool_state)
      when v_event_type is not null then v_event_type
      else null
    end;
    v_changed := p_after_seq is null
      or (v_progress_seq is not null and v_progress_seq > p_after_seq);

    if v_status in ('completed','failed','cancelled') then
      return pg_catalog.jsonb_build_object(
        'kind','final','job_id',p_job_id,'status',v_status,'terminal',true,
        'ready',(v_status='completed' and v_error is null
          and coalesce(pg_catalog.length(pg_catalog.btrim(v_response_text)),0)>0
          and coalesce(v_result_conversation_id,v_job_conversation_id) is not null),
        'timed_out',false,'changed',true,
        'conversation_id',coalesce(v_result_conversation_id,v_job_conversation_id),
        'response_text',v_response_text,'error',v_error,
        'heartbeat_at',v_heartbeat_at,'completed_at',v_completed_at,
        'progress_seq',v_progress_seq,'progress_text',v_progress_text,
        'progress_event_type',v_event_type,'tool_name',v_tool_name,'tool_state',v_tool_state
      );
    end if;

    if v_changed then
      return pg_catalog.jsonb_build_object(
        'kind','progress','job_id',p_job_id,'status',v_status,'terminal',false,
        'ready',false,'timed_out',false,'changed',true,
        'conversation_id',v_job_conversation_id,'response_text',v_response_text,'error',v_error,
        'heartbeat_at',v_heartbeat_at,'completed_at',null,
        'progress_seq',v_progress_seq,'progress_text',v_progress_text,
        'progress_event_type',v_event_type,'tool_name',v_tool_name,'tool_state',v_tool_state
      );
    end if;

    if p_timeout_seconds=0 or pg_catalog.clock_timestamp()>=v_deadline then
      return pg_catalog.jsonb_build_object(
        'kind','progress','job_id',p_job_id,'status',v_status,'terminal',false,
        'ready',false,'timed_out',(p_timeout_seconds>0),'changed',false,
        'conversation_id',v_job_conversation_id,'response_text',v_response_text,'error',v_error,
        'heartbeat_at',v_heartbeat_at,'completed_at',null,
        'progress_seq',v_progress_seq,'progress_text',v_progress_text,
        'progress_event_type',v_event_type,'tool_name',v_tool_name,'tool_state',v_tool_state
      );
    end if;

    perform pg_catalog.pg_sleep(least(
      v_sleep_seconds,
      greatest(0.0,extract(epoch from (v_deadline-pg_catalog.clock_timestamp())))
    ));
  end loop;
end;
$function$;

revoke all on function private.wait_agent_job(uuid,bigint,integer,integer) from public,anon,authenticated;
grant execute on function private.wait_agent_job(uuid,bigint,integer,integer) to service_role;

