-- Antigravity ChatGPT Agent Bridge schema
-- Apply to the dedicated Supabase project used only for ChatGPT <-> Termux/AGY jobs.

begin;

create table if not exists public.agent_jobs (
  id uuid primary key default gen_random_uuid(),
  idempotency_key text not null unique default gen_random_uuid()::text,
  requested_by text not null default 'chatgpt',
  status text not null default 'pending'
    check (status in ('pending','claimed','running','completed','failed','cancelled')),
  request jsonb not null default '{}'::jsonb,
  conversation_id text,
  worker_id text,
  claim_token uuid,
  attempts integer not null default 0 check (attempts >= 0),
  heartbeat_at timestamptz,
  lease_expires_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  error jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agent_jobs_request_object check (jsonb_typeof(request) = 'object'),
  constraint agent_jobs_prompt_required check (length(btrim(coalesce(request->>'prompt',''))) > 0)
);

create index if not exists agent_jobs_queue_idx
  on public.agent_jobs(status, created_at) where status='pending';
create index if not exists agent_jobs_worker_lease_idx
  on public.agent_jobs(worker_id, lease_expires_at) where status in ('claimed','running');

create table if not exists public.agent_events (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.agent_jobs(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint agent_events_payload_object check (jsonb_typeof(payload)='object')
);
create index if not exists agent_events_job_idx on public.agent_events(job_id,id);

create table if not exists public.agent_results (
  job_id uuid primary key references public.agent_jobs(id) on delete cascade,
  conversation_id text,
  response_text text not null default '',
  bot_message jsonb,
  subagents jsonb not null default '[]'::jsonb,
  tasks jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  constraint agent_results_subagents_array check (jsonb_typeof(subagents)='array'),
  constraint agent_results_tasks_array check (jsonb_typeof(tasks)='array')
);

alter table public.agent_jobs enable row level security;
alter table public.agent_events enable row level security;
alter table public.agent_results enable row level security;

revoke all on table public.agent_jobs from anon, authenticated;
revoke all on table public.agent_events from anon, authenticated;
revoke all on table public.agent_results from anon, authenticated;

grant select,insert,update,delete on table public.agent_jobs to service_role;
grant select,insert,update,delete on table public.agent_events to service_role;
grant select,insert,update,delete on table public.agent_results to service_role;
grant usage,select on sequence public.agent_events_id_seq to service_role;

create or replace function public.claim_agent_job(p_worker_id text,p_lease_seconds integer default 120)
returns setof public.agent_jobs
language plpgsql security invoker set search_path=public
as $$
begin
  if p_worker_id is null or btrim(p_worker_id)='' then raise exception 'worker_id_required'; end if;
  if p_lease_seconds<30 or p_lease_seconds>900 then raise exception 'invalid_lease_seconds'; end if;
  return query
  with candidate as (
    select id from public.agent_jobs
    where status='pending'
    order by created_at,id
    for update skip locked
    limit 1
  )
  update public.agent_jobs j
  set status='claimed',worker_id=p_worker_id,claim_token=gen_random_uuid(),
      attempts=j.attempts+1,heartbeat_at=now(),
      lease_expires_at=now()+make_interval(secs=>p_lease_seconds),
      updated_at=now(),error=null
  from candidate c where j.id=c.id
  returning j.*;
end;
$$;

create or replace function public.heartbeat_agent_job(
  p_job_id uuid,p_worker_id text,p_claim_token uuid,p_lease_seconds integer default 120
) returns boolean
language plpgsql security invoker set search_path=public
as $$
declare n integer;
begin
  if p_lease_seconds<30 or p_lease_seconds>900 then raise exception 'invalid_lease_seconds'; end if;
  update public.agent_jobs
  set heartbeat_at=now(),lease_expires_at=now()+make_interval(secs=>p_lease_seconds),updated_at=now()
  where id=p_job_id and worker_id=p_worker_id and claim_token=p_claim_token
    and status in ('claimed','running');
  get diagnostics n=row_count; return n=1;
end;
$$;

create or replace function public.mark_agent_job_running(
  p_job_id uuid,p_worker_id text,p_claim_token uuid,p_conversation_id text default null,p_lease_seconds integer default 120
) returns boolean
language plpgsql security invoker set search_path=public
as $$
declare n integer;
begin
  update public.agent_jobs
  set status='running',conversation_id=coalesce(nullif(p_conversation_id,''),conversation_id),
      started_at=coalesce(started_at,now()),heartbeat_at=now(),
      lease_expires_at=now()+make_interval(secs=>p_lease_seconds),updated_at=now()
  where id=p_job_id and worker_id=p_worker_id and claim_token=p_claim_token
    and status in ('claimed','running');
  get diagnostics n=row_count; return n=1;
end;
$$;

create or replace function public.bind_agent_job_conversation(
  p_job_id uuid,p_worker_id text,p_claim_token uuid,p_conversation_id text
) returns boolean
language plpgsql security invoker set search_path=public
as $$
declare n integer;
begin
  if p_conversation_id is null or btrim(p_conversation_id)='' then return false; end if;
  update public.agent_jobs set conversation_id=p_conversation_id,updated_at=now()
  where id=p_job_id and worker_id=p_worker_id and claim_token=p_claim_token
    and status in ('claimed','running');
  get diagnostics n=row_count; return n=1;
end;
$$;

create or replace function public.complete_agent_job(
  p_job_id uuid,p_worker_id text,p_claim_token uuid,p_conversation_id text,p_response_text text,
  p_bot_message jsonb default null,p_subagents jsonb default '[]'::jsonb,p_tasks jsonb default '[]'::jsonb
) returns boolean
language plpgsql security invoker set search_path=public
as $$
declare n integer;
begin
  update public.agent_jobs
  set status='completed',conversation_id=coalesce(nullif(p_conversation_id,''),conversation_id),
      completed_at=now(),heartbeat_at=now(),lease_expires_at=null,updated_at=now(),error=null
  where id=p_job_id and worker_id=p_worker_id and claim_token=p_claim_token
    and status in ('claimed','running');
  get diagnostics n=row_count;
  if n<>1 then return false; end if;

  insert into public.agent_results(job_id,conversation_id,response_text,bot_message,subagents,tasks,created_at)
  values(p_job_id,nullif(p_conversation_id,''),coalesce(p_response_text,''),p_bot_message,
         coalesce(p_subagents,'[]'::jsonb),coalesce(p_tasks,'[]'::jsonb),now())
  on conflict(job_id) do update set
    conversation_id=excluded.conversation_id,response_text=excluded.response_text,
    bot_message=excluded.bot_message,subagents=excluded.subagents,tasks=excluded.tasks,
    created_at=excluded.created_at;
  return true;
end;
$$;

create or replace function public.fail_agent_job(
  p_job_id uuid,p_worker_id text,p_claim_token uuid,p_error jsonb
) returns boolean
language plpgsql security invoker set search_path=public
as $$
declare n integer;
begin
  update public.agent_jobs
  set status='failed',completed_at=now(),heartbeat_at=now(),lease_expires_at=null,
      updated_at=now(),error=coalesce(p_error,'{"code":"unknown"}'::jsonb)
  where id=p_job_id and worker_id=p_worker_id and claim_token=p_claim_token
    and status in ('claimed','running');
  get diagnostics n=row_count; return n=1;
end;
$$;

create or replace function public.requeue_stale_claimed_agent_job(
  p_job_id uuid,p_worker_id text,p_claim_token uuid
) returns boolean
language plpgsql security invoker set search_path=public
as $$
declare n integer;
begin
  update public.agent_jobs
  set status='pending',worker_id=null,claim_token=null,heartbeat_at=null,lease_expires_at=null,updated_at=now()
  where id=p_job_id and worker_id=p_worker_id and claim_token=p_claim_token
    and status='claimed' and started_at is null and lease_expires_at<now();
  get diagnostics n=row_count; return n=1;
end;
$$;

revoke all on function public.claim_agent_job(text,integer) from public,anon,authenticated;
revoke all on function public.heartbeat_agent_job(uuid,text,uuid,integer) from public,anon,authenticated;
revoke all on function public.mark_agent_job_running(uuid,text,uuid,text,integer) from public,anon,authenticated;
revoke all on function public.bind_agent_job_conversation(uuid,text,uuid,text) from public,anon,authenticated;
revoke all on function public.complete_agent_job(uuid,text,uuid,text,text,jsonb,jsonb,jsonb) from public,anon,authenticated;
revoke all on function public.fail_agent_job(uuid,text,uuid,jsonb) from public,anon,authenticated;
revoke all on function public.requeue_stale_claimed_agent_job(uuid,text,uuid) from public,anon,authenticated;

grant execute on function public.claim_agent_job(text,integer) to service_role;
grant execute on function public.heartbeat_agent_job(uuid,text,uuid,integer) to service_role;
grant execute on function public.mark_agent_job_running(uuid,text,uuid,text,integer) to service_role;
grant execute on function public.bind_agent_job_conversation(uuid,text,uuid,text) to service_role;
grant execute on function public.complete_agent_job(uuid,text,uuid,text,text,jsonb,jsonb,jsonb) to service_role;
grant execute on function public.fail_agent_job(uuid,text,uuid,jsonb) to service_role;
grant execute on function public.requeue_stale_claimed_agent_job(uuid,text,uuid) to service_role;

commit;
notify pgrst,'reload schema';
